#!/usr/bin/env python3
"""
Generate src/autogenerated/Embeds.hpp from GLSL shader sources.
"""
import os
import sys

SHADERS = [
    ("src/graphics/ff.vert", "vertShaderBytes"),
    ("src/graphics/ff.frag", "fragShaderBytes"),
]

OUT = "src/autogenerated/Embeds.hpp"


def emit(path, name, out):
    with open(path, "rb") as f:
        data = f.read()
    out.write(f"\nstatic char {name}[] = {{")
    out.write(",".join(f"0x{b:X}" for b in data))
    out.write(",0};\n")


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as out:
        out.write("#pragma once\n// Auto-generated by scripts/gen_embeds.py -- do not edit.\n")
        for path, name in SHADERS:
            if not os.path.exists(path):
                print(f"warning: {path} missing", file=sys.stderr)
                continue
            emit(path, name, out)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
